[package]
name = "mr-metal"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mr-core = { workspace = true }
mr-grid = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.29"

[dev-dependencies]
mr-cpu = { workspace = true }
mr-fixtures = { workspace = true }
mr-oracle = { workspace = true }
