[package]
name = "mr-bench"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mr-core = { workspace = true }

[dev-dependencies]
criterion = "0.5"
mr-fixtures = { workspace = true }
mr-cpu = { workspace = true }

[[bench]]
name = "route"
harness = false
