[package]
name = "mr-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "mr_cli"
path = "src/lib.rs"

[[bin]]
name = "metalroute"
path = "src/main.rs"

[dependencies]
mr-core = { workspace = true }
mr-srj = { workspace = true }
mr-cpu = { workspace = true }
mr-bench = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
